let suggestions = [
    "Airedale Terrier",
    "Akbash[6]",
    "Afghan Hound",
    "Akita[7]",
    "Aksaray Malaklisi",
    "Alano Español[8]",
    "Alapaha Blue Blood ",
    "Alaskan husky",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "Alopekis",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American bully",
    "American Cocker Spa",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless",
    "American Pit Bull T",
    "American Staffordsh",
    "American Water Span",
    "Andalusian Hound",
    "Anglo-Français de P",
    "Appenzeller Sennenh",
    "Ariegeois[25]",
    "Armant[26]",
    "Armenian Gampr dog",
    "Artois Hound[27]",
    "Bakharwal dog",
    "Banjara Hound[35]",
    "Barbado da Terceira[36]",
    "Boykin Spaniel[72]",
    "Bracco Italiano[73]",
    "Braque d'Auvergne[74]",
    "Braque de l'Ariège[74]",
    "Braque du Bourbonnais[75]",
    "Braque Francais[76]",
    "Braque Saint-Germain[75]",
    "Briard[48]",
    "Briquet Griffon Vendéen[77]",
    "Brittany[60]",
    "Broholmer[78]",
    "Bruno Jura Hound[79]",
    "Brussels Griffon[80]",
    "Bucovina Shepherd Dog[81]",
    "Bull Arab",
    "Bull Terrier[82]",
    "Bulldog[83]",
    "Bullmastiff[83]",
    "Bully Kutta",
    "Burgos Pointer[84]",
    "Buryat-Mongolian Wolfhound",
    "Ca Mè Mallorquí[85]",
    "Cairn Terrier[86]",
    "Campeiro Bulldog",
    "Can de Chira",
    "Can de Palleiro",
    "Canaan Dog[87]",
    "Canadian Eskimo Dog[12]",
    "Cane Corso[4]",
    "Cane di Oropa",
    "Chesapeake Bay Retriever[103]",
    "Chien Français Blanc et Noir[",
    "Chien Français Blanc et Orang",
    "Chien Français Tricolore[104]",
    "Chihuahua[106]",
    "Chilean Terrier",
    "Chinese Crested Dog[107]",
    "Chinook[108]",
    "Chippiparai[109]",
    "Chongqing dog",
    "Chortai[110]",
    "Chow Chow[111]",
    "Chukotka sled dog",
    "Cimarrón Uruguayo",
    "Cirneco dell'Etna[112]",
    "Clumber Spaniel[113]",
    "Colombian fino hound",
    "Continental bulldog",
    "Coton de Tulear[114]",
    "Cretan Hound[115]",
    "Croatian Sheepdog[95]",
    "Danish Spitz",
    "Danish-Swedish Farmdog[120]",
    "Denmark Feist[121]",
    "Dingo [note 1]",
    "Dobermann[44]",
    "Dogo Argentino[123]",
    "Dogo Guatemalteco",
    "Dogo Sardesco",
    "Dogue Brasileiro[123]",
    "Dogue de Bordeaux[124]",
    "Drentse Patrijshond[125]",
    "Drever[126]",
    "Dunker[127]",
    "Dutch Shepherd[128]",
    "Dutch Smoushond[129]",
    "East Siberian Laika[130]",
    "East European Shepherd[131]",
    "Ecuadorian Hairless Dog[132]",
    "English Cocker Spaniel[133]",
    "English Foxhound[134]",
    "English Mastiff[124]",
    "English Setter[135]",
    "English Shepherd[136]",
    "English Springer Spaniel[137",
    "English Toy Terrier (Black &",
    "Entlebucher Mountain Dog[139",
    "Estonian Hound[140]",
    "Estrela Mountain Dog[89]",
    "Eurasier[111]",
    "Field Spaniel[141]",
    "Fila Brasileiro[123]",
    "Finnish Hound[142]",
    "Finnish Lapphund[143]",
    "Finnish Spitz[144]",
    "Flat-Coated Retriever[145]",
    "French Bulldog[146]",
    "French Spaniel[147]",
    "Galgo Español[148]",
    "Garafian Shepherd[149]",
    "Gascon Saintongeois[23]",
    "Georgian Shepherd",
    "German Hound",
    "German Longhaired Pointer[150]",
    "German Pinscher[1]",
    "German Roughhaired Pointer[151",
    "German Shepherd[152]",
    "German Shorthaired Pointer[150",
    "German Spaniel[113]",
    "German Spitz[153]",
    "German Wirehaired Pointer[150]",
    "Giant Schnauzer[154]",
    "Glen of Imaal Terrier[155]",
    "Golden Retriever[156]",
    "Gończy Polski[157]",
    "Gordon Setter[135]",
    "Grand Anglo-Français Blanc et Noir[158]",
    "Grand Anglo-Français Blanc et Orange",
    "Grand Anglo-Français Tricolore[158]",
    "Grand Basset Griffon Vendéen[159]",
    "Grand Bleu de Gascogne[160]",
    "Grand Griffon Vendéen[77]",
    "Great Dane[161]",
    "Greater Swiss Mountain Dog[139]",
    "Greek Harehound[162]",
    "Greek Shepherd[163]",
    "Greenland Dog[164]",
    "Greyhound[66]",
    "Griffon Bleu de Gascogne[41]",
    "Griffon Fauve de Bretagne[42]",
    "Griffon Nivernais[40]",
    "Gull Dong",
    "Gull Terrier",
    "Hällefors Elkhound",
    "Halden Hound",
    "Hamiltonstövare[165]",
    "Hanover Hound[166]",
    "Harrier[167]",
    "Havanese[63]",
    "Himalayan Sheepdog[168]",
    "Hierran Wolfdog",
    "Hokkaido[7]",
    "Hovawart[169]",
    "Huntaway[170]",
    "Hygen Hound[142]",
    "Ibizan Hound[112]",
    "Icelandic Sheepdog[171]",
    "Indian pariah dog",
    "Indian Spitz",
    "Irish Red and White Setter[172]",
    "Irish Setter[172]",
    "Istrian Coarse-haired Hound[175]",
    "Istrian Shorthaired Hound[67]",
    "Italian Greyhound[176]",
    "Jack Russell Terrier[177]",
    "Jagdterrier[102]",
    "Japanese Chin[178]",
    "Japanese Spitz[179]",
    "Japanese Terrier[180]",
    "Jindo[181]",
    "Jonangi",
    "Kai Ken",
    "Kaikadi[182]",
    "Kangal Shepherd Dog[6]",
    "Kanni[35]",
    "Karakachan dog",
    "Karelian Bear Dog[183]",
    "Kars[184]",
    "Karst Shepherd[185]",
    "Keeshond[186]",
    "Kerry Beagle[45]",
    "Kerry Blue Terrier[187]",
    "Khala [188]",
    "King Charles Spaniel[178]",
    "King Shepherd[69]",
    "Kintamani",
    "Kishu[189]",
    "Kokoni",
    "Kombai[190]",
    "Komondor[191]",
    "Kooikerhondje[192]",
    "Koolie",
    "Koyun dog",
    "Kromfohrländer[180]",
    "Kuchi[193]",
    "Kuvasz[194]",
    "L–R",
    "Labrador Retriever[195]",
    "Lagotto Romagnolo[196]",
    "Lakeland Terrier[65]",
    "Lancashire Heeler[29]",
    "Landseer[197]",
    "Lapponian Herder[144]",
    "Large Münsterländer[198]",
    "Leonberger[123]",
    "Levriero Sardo",
    "Lhasa Apso[199]",
    "Lithuanian Hound[140]",
    "Löwchen[114]",
    "Lupo Italiano",
    "Mackenzie River husky",
    "Magyar agár[200]",
    "Mahratta Greyhound[201]",
    "Maltese[52]",
    "Manchester Terrier[138]",
    "Maneto[202]",
    "Maremmano-Abruzzese Sheepdog[50]",
    "McNab dog",
    "Miniature American Shepherd",
    "Miniature Bull Terrier[82]",
    "Miniature Fox Terrier",
    "Miniature Pinscher[33]",
    "Miniature Schnauzer[203]",
    "Molossus of Epirus",
    "Montenegrin Mountain Hound[204]",
    "Mountain Cur[162]",
    "Mountain Feist[121]",
    "Mucuchies[205]",
    "Mudhol Hound[206]",
    "Mudi[207]",
    "Neapolitan Mastiff[208]",
    "Nenets Herding Laika",
    "New Guinea singing dog",
    "New Zealand Heading Dog",
    "Newfoundland[209]",
    "Norfolk Terrier[86]",
    "Norrbottenspets[210]",
    "Northern Inuit Dog",
    "Norwegian Buhund[171]",
    "Norwegian Elkhound[211]",
    "Norwegian Lundehund[212]",
    "Norwich Terrier[213]",
    "Nova Scotia Duck Tolling Retriev",
    "Old Croatian Sighthound",
    "Old Danish Pointer[214]",
    "Old English Sheepdog[54]",
    "Old English Terrier[215]",
    "Olde English Bulldogge[14]",
    "Otterhound[134]",
    "Pachon Navarro",
    "Pampas Deerhound",
    "Papillon[216]",
    "Parson Russell Terrier[217]",
    "Pastore della Lessinia e del Lag",
    "Patagonian Sheepdog",
    "Patterdale Terrier[218]",
    "Pekingese[219]",
    "Pembroke Welsh Corgi[92]",
    "Perro Majorero",
    "Perro de Pastor Mallorquin",
    "Perro de Presa Canario[220]",
    "Perro de Presa Mallorquin[221]",
    "Peruvian Inca Orchid[222]",
    "Petit Basset Griffon Vendéen",
    "Petit Bleu de Gascogne[160]",
    "Phalène[216]",
    "Pharaoh Hound[223]",
    "Phu Quoc Ridgeback",
    "Picardy Spaniel[147]",
    "Plummer Terrier[218]",
    "Plott Hound[224]",
    "Podenco Canario[87]",
    "Podenco Valenciano",
    "Pointer[145]",
    "Poitevin[175]",
    "Polish Greyhound[225]",
    "Polish Hound[226]",
    "Polish Lowland Sheepdog[227]",
    "Polish Tatra Sheepdog[228]",
    "Pomeranian[229]",
    "Pont-Audemer Spaniel[230]",
    "Poodle[231]",
    "Porcelaine[53]",
    "Portuguese Podengo[232]",
    "Portuguese Pointer[233]",
    "Portuguese Water Dog[234]",
    "Posavac Hound[235]",
    "Pražský Krysařík[236]",
    "Pshdar dog",
    "Pudelpointer[214]",
    "Pug[146]",
    "Puli[234]",
    "Pumi[191]",
    "Pungsan dog",
    "Pyrenean Mastiff[237]",
    "Pyrenean Mountain Dog[237]",
    "Pyrenean Sheepdog[209]",
    "Rafeiro do Alentejo[238]",
    "Rajapalayam[239]",
    "Rampur Greyhound[29]",
    "Rat Terrier[240]",
    "Ratonero Bodeguero Andaluz",
    "Ratonero Mallorquin",
    "Ratonero Murciano",
    "Ratonero Valenciano",
    "Redbone Coonhound[241]",
    "Rhodesian Ridgeback[166]",
    "Romanian Mioritic Shepherd Dog",
    "Romanian Raven Shepherd Dog[95]",
    "Rottweiler[161]",
    "Rough Collie[64]",
    "Russian Spaniel",
    "Russian Toy",
    "Russo-European Laika[130]",
    "Ryukyu Inu",
    "S–Z",
    "Saarloos Wolfdog[116]",
    "Sabueso Español[242]",
    "Saint Bernard[197]",
    "Saint Hubert Jura Hound[79]",
    "Saint-Usuge Spaniel",
    "Saluki[148]",
    "Samoyed[179]",
    "Sapsali",
    "Sarabi dog[243]",
    "Sardinian Shepherd Dog",
    "Šarplaninac[95]",
    "Schapendoes[51]",
    "Schillerstövare[126]",
    "Schipperke[244]",
    "Schweizer Laufhund[105]",
    "Schweizerischer Niederlaufhund",
    "Scottish Deerhound[174]",
    "Scottish Terrier[246]",
    "Sealyham Terrier[119]",
    "Segugio dell'Appennino",
    "Segugio Italiano[242]",
    "Segugio Maremmano",
    "Serbian Hound[247]",
    "Serbian Tricolour Hound[204]",
    "Serrano Bulldog",
    "Shar Pei",
    "Shetland Sheepdog[248]",
    "Shiba Inu[249]",
    "Shih Tzu[199]",
    "Shikoku[108]",
    "Shiloh Shepherd[236]",
    "Siberian Husky[164]",
    "Silken Windhound",
    "Silky Terrier[31]",
    "Sinhala Hound",
    "Skye Terrier[246]",
    "Sloughi[34]",
    "Slovakian Wirehaired Pointer[151",
    "Slovenský Cuvac[194]",
    "Slovenský Kopov[226]",
    "Smalandstövare[157]",
    "Small Greek domestic dog",
    "Small Münsterländer[198]",
    "Smooth Collie[248]",
    "Smooth Fox Terrier[250]",
    "Soft-Coated Wheaten Terrier[155]",
    "South Russian Ovcharka[251]",
    "Spanish Mastiff[208]",
    "Spanish Water Dog[173]",
    "Spinone Italiano[73]",
    "Sporting Lucas Terrier[120]",
    "Stabyhoun[125]",
    "Staffordshire Bull Terrier[252]",
    "Standard Schnauzer[154]",
    "Stephens Stock[253]",
    "Styrian Coarse-haired Hound[13]",
    "Sussex Spaniel[141]",
    "Swedish Elkhound[254]",
    "Swedish Lapphund[254]",
    "Swedish Vallhund[70]",
    "Swedish White Elkhound",
    "Taigan[201]",
    "Taiwan Dog",
    "Tamaskan Dog",
    "Tazy",
    "Teddy Roosevelt Terrier",
    "Telomian",
    "Tenterfield Terrier",
    "Terrier Brasileiro[240]",
    "Thai Bangkaew Dog",
    "Thai Ridgeback[255]",
    "Tibetan Kyi Apso",
    "Tibetan Mastiff[256]",
    "Tibetan Spaniel[257]",
    "Tibetan Terrier[257]",
    "Torkuz[168]",
    "Tornjak[168]",
    "Tosa[258]",
    "Toy Fox Terrier[68]",
    "Toy Manchester Terrier[138]",
    "Transylvanian Hound[259]",
    "Treeing Cur",
    "Treeing Feist[260]",
    "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound[224]",
    "Trigg Hound[261]",
    "Tyrolean Hound[262]",
    "Vikhan[263]",
    "Villano de Las Encartaciones",
    "Villanuco de Las Encartaciones",
    "Vizsla[264]",
    "Volpino Italiano[229]",
    "Weimaraner[265]",
    "Welsh Sheepdog",
    "Welsh Springer Spaniel[137]",
    "Welsh Terrier[187]",
    "West Country Harrier[266]",
    "West Highland White Terrier[213]",
    "West Siberian Laika[183]",
    "Westphalian Dachsbracke[126]",
    "Wetterhoun[230]",
    "Whippet[200]",
    "White Shepherd",
    "White Swiss Shepherd Dog[62]",
    "Wire Fox Terrier[250]",
    "Wirehaired Pointing Griffon[267]",
    "Wirehaired Vizsla",
    "Xiasi Dog",
    "Xoloitzcuintle[268]",
    "Yakutian Laika",
    "Yorkshire Terrier[269]",
    "Zerdava",
    "Extinct breeds, varieties and ty",
    "Alaunt[270]",
    "Alpine Mastiff[271]",
    "Argentine Polar Dog",
    "Belgian Mastiff[272]",
    "Black and Tan Terrier[273]",
    "Blue Paul Terrier[274]",
    "Braque Dupuy[275]",
    "Bull and terrier",
    "Bullenbeisser[276]",
    "Chien-gris[277]",
    "Chiribaya Dog",
    "Cordoba Fighting Dog",
    "Cumberland Sheepdog",
    "Cur[278]",
    "Dalbo dog[279]",
    "Dogo cubano[280]",
    "Dumfriesshire Black and Tan Foxh",
    "English Water Spaniel",
    "English White Terrier[273]",
    "Fila da Terceira",
    "Grand Fauve de Bretagne[42]",
    "Halls Heeler[281]",
    "Hare Indian Dog",
    "Hawaiian Poi Dog",
    "Kurī[282]",
    "Lapponian Shepherd",
    "Limer",
    "Marquesan Dog",
    "Molossus",
    "Moscow Water Dog",
    "Norfolk Spaniel",
    "North Country Beagle",
    "Old Croatian Sighthound",
    "Old English Bulldog",
    "Old Spanish Pointer",
    "Paisley Terrier",
    "Polynesian Dog",
    "Rache",
    "Rastreador Brasileiro[283]",
    "Saint John's water dog",
    "Sakhalin Husky",
    "Salish Wool Dog",
    "Sleuth hound",
    "Southern Hound[76]",
    "Tahitian Dog",
    "Tahltan Bear Dog[284]",
    "Talbot Hound[54]",
    "Tesem",
    "Toy Bulldog",
    "Toy Trawler Spaniel",
    "Turnspit dog",
    "Tweed Water Spaniel[285]",
    "Welsh Hillman"
    ]